version: "3.8"

networks:
  bigdata:
    driver: bridge

services:
  # Postgres for Hive Metastore
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: hive
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
    ports:
      - "5432:5432"
    networks: [bigdata]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hive -d hive"]
      interval: 5s
      timeout: 5s
      retries: 20

  # Hadoop (single node)
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=hadoop
    ports:
      - "9870:9870"  # NN UI
      - "8020:8020"  # RPC
    volumes:
      - namenode:/hadoop/dfs/name
    networks: [bigdata]
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:9870 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 50

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - SERVICE_PRECONDITION=namenode:9870
    ports:
      - "9864:9864" # DN UI
    volumes:
      - datanode:/hadoop/dfs/data
    networks: [bigdata]
    depends_on: [namenode]

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
      - SERVICE_PRECONDITION=namenode:9870 datanode:9864
    ports:
      - "8088:8088"  # YARN UI
    networks: [bigdata]
    depends_on: [namenode, datanode]

  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
      - SERVICE_PRECONDITION=namenode:9870 datanode:9864 resourcemanager:8088
    networks: [bigdata]
    depends_on: [resourcemanager]

  # Hive Metastore service (thrift on 9083)
  hive-metastore:
    image: bde2020/hive:3.1.3
    container_name: hive-metastore
    command: ["bash", "-lc", "schematool -dbType postgres -initSchema --userName hive --passWord hive --url jdbc:postgresql://postgres:5432/hive || true && hive --service metastore"]
    environment:
      - HIVE_HOME=/opt/hive
      - HADOOP_HOME=/opt/hadoop
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
      - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
      - SERVICE_PRECONDITION=namenode:9870 datanode:9864 resourcemanager:8088 postgres:5432
      - HIVE_CONF_DIR=/opt/hive/conf
    volumes:
      - ./conf/hive-site.xml:/opt/hive/conf/hive-site.xml:ro
    ports:
      - "9083:9083"
    networks: [bigdata]
    depends_on:
      postgres:
        condition: service_healthy
      resourcemanager:
        condition: service_started

  # HiveServer2 (JDBC on 10000)
  hive-server:
    image: bde2020/hive:3.1.3
    container_name: hive-server
    command: ["bash", "-lc", "hive --service hiveserver2"]
    environment:
      - HIVE_HOME=/opt/hive
      - HADOOP_HOME=/opt/hadoop
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
      - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
      - HIVE_CONF_DIR=/opt/hive/conf
      - SERVICE_PRECONDITION=hive-metastore:9083
    volumes:
      - ./conf/hive-site.xml:/opt/hive/conf/hive-site.xml:ro
    ports:
      - "10000:10000"
    networks: [bigdata]
    depends_on: [hive-metastore]

volumes:
  namenode:
  datanode:
