networks:
  bigdata: { driver: bridge }

volumes:
  namenode: {}
  datanode: {}
  hive_derby: {}   # persists the embedded Derby DB

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    environment: [CLUSTER_NAME=hadoop]
    ports: ["9870:9870","8020:8020"]
    volumes: [namenode:/hadoop/dfs/name]
    networks: [bigdata]

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - SERVICE_PRECONDITION=namenode:9870
    ports: ["9864:9864"]
    volumes: [datanode:/hadoop/dfs/data]
    networks: [bigdata]
    depends_on: [namenode]

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
      - SERVICE_PRECONDITION=namenode:9870 datanode:9864
    ports: ["8088:8088"]
    networks: [bigdata]
    depends_on: [namenode, datanode]

  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
      - SERVICE_PRECONDITION=namenode:9870 datanode:9864 resourcemanager:8088
    networks: [bigdata]
    depends_on: [resourcemanager]

  # One-shot Derby schema init (writes to /opt/hive/data)
  hive-derby-init:
    image: apache/hive:3.1.3
    container_name: hive-derby-init
    user: "0:0"                                 # run as root so it can create DB files
    environment:
      HIVE_CUSTOM_CONF_DIR: /hive_custom_conf
    volumes:
      - hive_derby:/opt/hive/data
      - ./conf/hadoop:/hive_custom_conf:ro
    entrypoint: [ "bash","-lc",
      "mkdir -p /opt/hive/data && \
       schematool -dbType derby -initSchema || schematool -dbType derby -validate" ]
    networks: [bigdata]
    depends_on: [namenode, datanode, resourcemanager, nodemanager]

  # HiveServer2 with embedded Derby metastore
  hive-server:
    image: apache/hive:3.1.3
    container_name: hive-server
    user: "0:0"                                 # ensure write access to /opt/hive/data
    environment:
      SERVICE_NAME: hiveserver2
      HIVE_CUSTOM_CONF_DIR: /hive_custom_conf
      SERVICE_OPTS: >-
        -Djavax.jdo.option.ConnectionURL=jdbc:derby:;databaseName=/opt/hive/data/derby;create=true
        -Djavax.jdo.option.ConnectionDriverName=org.apache.derby.jdbc.EmbeddedDriver
        -Dhive.metastore.warehouse.dir=/user/hive/warehouse
        -Dhive.server2.thrift.bind.host=0.0.0.0
        -Dhive.server2.thrift.port=10000
    volumes:
      - hive_derby:/opt/hive/data
      - ./conf/hadoop:/hive_custom_conf:ro      # provides fs.defaultFS -> namenode
    ports:
      - "10000:10000"                           # optional (host JDBC)
      - "10002:10002"                           # HS2 web UI
    networks: [bigdata]
    depends_on:
      - hive-derby-init
